repos:
  - repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
      - id: black
        language_version: python3
        files: \.py$

  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: \.py$

  - repo: local
    hooks:
      - id: pack-packages
        name: Pack Python packages
        entry: ./dev-scripts/pack_packages.sh
        language: script
        files: ^baliky/
        pass_filenames: false
        stages: [pre-push]

      # - id: copy-conda-env
      #   name: Copy conda-environment.yml to PGIS2/soubory
      #   entry: ./dev-scripts/copy_conda_env.sh
      #   language: script
      #   files: ^conda-environment.yml$
      #   pass_filenames: false
      #   stages: [pre-commit]
