name: env-pgis2

channels:
  - conda-forge
  - defaults

solver: libmamba

dependencies:
  - python=3.14
  - pip
  # pgis2
  - GDAL
  - fiona
  - rasterio
  - shapely
  - pyproj
  # data frames + geo data frames
  - pandas
  - geopandas
  - polars
  # visualization
  - matplotlib
  - plotnine
  # dev
  - poetry
  # notebooks
  - jupyter
  - nbformat
  # VS Code extensions
  - black 
  - isort
  - mypy
  - pep8
  - flake8
  - pylint
  # SQL
  - psycopg
  # install using pip
  - pip:
    # pgis2
    # - geopolars
